{{- $name := include "catalog.fullname" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "catalog.name" . }}
    chart: {{ template "catalog.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  DatabaseSettings__ConnectionString: mongodb://catalogdb:27017
  DatabaseSettings__DatabaseName: CatalogDb
  DatabaseSettings__CollectionName: Products
  ElasticConfiguration__Uri: http://elasticsearch:9200